# local ??
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/mydb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: cache-server
      port: 6379

logging:
  level:
    # Redis ??? ?? ??? ????? ??
    org.springframework.cache: trace

---
# prod ??
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://redis-test.c0m4oycvnxbi.ap-northeast-2.rds.amazonaws.com:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: password